In [1]:
import pandas as pd
import numpy as np

In [2]:
project_dir = '~/RL_2024/'

In [3]:
df_train = pd.read_csv(project_dir + './data/traj_data_train.csv')
df_val = pd.read_csv(project_dir + './data/traj_data_val.csv')
df_test = pd.read_csv(project_dir + './data/traj_data_test.csv')

In [4]:
df_train[['traj', 'm:icustayid']].astype(int).drop_duplicates().to_csv(project_dir + 'data/icustayid_train.csv', index=False)
df_val[['traj', 'm:icustayid']].astype(int).drop_duplicates().to_csv(project_dir + 'data/icustayid_val.csv', index=False)
df_test[['traj', 'm:icustayid']].astype(int).drop_duplicates().to_csv(project_dir + 'data/icustayid_test.csv', index=False)

In [10]:
df = pd.read_csv('~/RL_2024/dataset/sepsis_final_data_RAW_withTimes_newActions.csv')

In [11]:
df

,traj,step,m:presumed_onset,m:charttime,m:icustayid,o:gender,o:mechvent,o:re_admission,o:age,o:Weight_kg,...,o:output_total,o:output_4hourly,r:reward,o:max_dose_vaso,o:input_4hourly,a:vaso,a:iv_OLD,a:iv,a:action_OLD,a:action
0,1,0,7.245590e+09,7.245486e+09,200003.0,0.0,0.0,0.0,17639.826435,78.699997,...,13617.0,520.0,0.0,0.0,50.0,0,2,1,10,5
1,1,1,7.245590e+09,7.245500e+09,200003.0,0.0,0.0,0.0,17639.826435,78.699997,...,13982.0,365.0,0.0,0.0,50.0,0,2,1,10,5
2,1,2,7.245590e+09,7.245515e+09,200003.0,0.0,0.0,0.0,17639.826435,78.699997,...,14262.0,280.0,0.0,0.0,50.0,0,2,1,10,5
3,1,3,7.245590e+09,7.245529e+09,200003.0,0.0,0.0,0.0,17639.826435,79.499997,...,14602.0,340.0,0.0,0.0,50.0,0,2,1,10,5
4,1,4,7.245590e+09,7.245544e+09,200003.0,0.0,0.0,0.0,17639.826435,79.699997,...,15142.0,540.0,0.0,0.0,50.0,0,2,1,10,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256568,19626,8,4.612800e+09,4.612888e+09,299995.0,0.0,0.0,0.0,8538.739340,49.000000,...,4660.0,600.0,0.0,0.0,0.0,0,0,0,0,0
256569,19626,9,4.612800e+09,4.612903e+09,299995.0,0.0,0.0,0.0,8538.739340,49.000000,...,5360.0,700.0,0.0,0.0,0.0,0,0,0,0,0
256570,19626,10,4.612800e+09,4.612917e+09,299995.0,0.0,0.0,0.0,8538.739340,58.700000,...,5360.0,0.0,0.0,0.0,0.0,0,0,0,0,0
256571,19626,11,4.612800e+09,4.612932e+09,299995.0,0.0,0.0,0.0,8538.739340,58.700000,...,5780.0,420.0,0.0,0.0,0.0,0,0,0,0,0
256572,19626,12,4.612800e+09,4.612946e+09,299995.0,0.0,0.0,0.0,8538.739340,92.000000,...,6300.0,520.0,1.0,0.0,0.0,0,0,0,0,0

In [12]:
df.columns

Index(['traj', 'step', 'm:presumed_onset', 'm:charttime', 'm:icustayid',
       'o:gender', 'o:mechvent', 'o:re_admission', 'o:age', 'o:Weight_kg',
       'o:GCS', 'o:HR', 'o:SysBP', 'o:MeanBP', 'o:DiaBP', 'o:RR', 'o:Temp_C',
       'o:FiO2_1', 'o:Potassium', 'o:Sodium', 'o:Chloride', 'o:Glucose',
       'o:Magnesium', 'o:Calcium', 'o:Hb', 'o:WBC_count', 'o:Platelets_count',
       'o:PTT', 'o:PT', 'o:Arterial_pH', 'o:paO2', 'o:paCO2', 'o:Arterial_BE',
       'o:HCO3', 'o:Arterial_lactate', 'o:SOFA', 'o:SIRS', 'o:Shock_Index',
       'o:PaO2_FiO2', 'o:cumulated_balance', 'o:SpO2', 'o:BUN', 'o:Creatinine',
       'o:SGOT', 'o:SGPT', 'o:Total_bili', 'o:INR', 'o:input_total',
       'o:output_total', 'o:output_4hourly', 'r:reward', 'o:max_dose_vaso',
       'o:input_4hourly', 'a:vaso', 'a:iv_OLD', 'a:iv', 'a:action_OLD',
       'a:action'],
      dtype='object')

In [16]:
with pd.option_context('display.max_columns', None):
    display(df[df['traj'] == 100])

,traj,step,m:presumed_onset,m:charttime,m:icustayid,o:gender,o:mechvent,o:re_admission,o:age,o:Weight_kg,o:GCS,o:HR,o:SysBP,o:MeanBP,o:DiaBP,o:RR,o:Temp_C,o:FiO2_1,o:Potassium,o:Sodium,o:Chloride,o:Glucose,o:Magnesium,o:Calcium,o:Hb,o:WBC_count,o:Platelets_count,o:PTT,o:PT,o:Arterial_pH,o:paO2,o:paCO2,o:Arterial_BE,o:HCO3,o:Arterial_lactate,o:SOFA,o:SIRS,o:Shock_Index,o:PaO2_FiO2,o:cumulated_balance,o:SpO2,o:BUN,o:Creatinine,o:SGOT,o:SGPT,o:Total_bili,o:INR,o:input_total,o:output_total,o:output_4hourly,r:reward,o:max_dose_vaso,o:input_4hourly,a:vaso,a:iv_OLD,a:iv,a:action_OLD,a:action
1389,100,0,4.915987e+09,4.915998e+09,200475.0,0.0,0.0,0.0,26088.061539,47.900000,13.000000,96.142857,91.571429,68.285714,60.714286,21.571429,36.960000,0.320000,3.200000,144.000000,116.000000,89.000000,1.200000,6.000000,7.500000,0.200000,64.000000,150.000000,17.900000,7.322000,85.066667,39.466667,-4.533333,17.000000,3.4,8.0,3.0,1.049922,265.833333,9150.0,97.428571,20.000000,1.1,29.000000,11.0,0.8,1.700000,9875.0,725.0,525.0,0.0,0.03,4875.0,1,4,4,21,21
1390,100,1,4.915987e+09,4.916012e+09,200475.0,0.0,0.0,0.0,26088.061539,99.099998,11.285714,89.714286,115.142857,74.809524,60.428571,24.428571,36.960000,0.302857,3.200000,144.000000,116.000000,89.000000,1.200000,6.000000,8.442857,0.200000,49.428571,52.885714,17.814286,7.450000,78.000000,37.000000,-1.000000,17.000000,2.0,10.0,2.0,0.779156,257.547170,9250.0,99.714286,33.000000,1.1,29.000000,11.0,0.8,1.700000,10250.0,1000.0,275.0,0.0,0.02,375.0,1,3,1,16,6
1391,100,2,4.915987e+09,4.916027e+09,200475.0,0.0,0.0,0.0,26088.061539,47.900000,10.000000,86.166667,107.833333,74.666667,64.166667,25.000000,36.960000,0.280000,3.600000,143.333333,116.666667,93.666667,1.466667,6.466667,9.533333,0.266667,37.666667,36.700000,17.800000,7.320000,56.000000,27.000000,-2.000000,15.400000,2.0,8.0,2.0,0.799073,200.000000,9005.0,97.833333,32.333333,1.1,29.000000,11.0,0.8,1.700000,10330.0,1325.0,325.0,0.0,0.00,80.0,0,2,1,10,5
1392,100,3,4.915987e+09,4.916041e+09,200475.0,0.0,0.0,0.0,26088.061539,47.900000,12.400000,88.800000,109.200000,68.800000,58.000000,23.600000,36.960000,0.280000,3.800000,143.000000,117.000000,96.000000,1.600000,6.700000,10.000000,0.300000,33.000000,36.700000,17.800000,7.450000,56.000000,27.000000,-2.000000,15.000000,2.0,8.0,2.0,0.813187,200.000000,8790.0,97.800000,32.000000,1.1,29.000000,11.0,0.8,1.700000,10430.0,1640.0,315.0,0.0,0.00,100.0,0,2,1,10,5
1393,100,4,4.915987e+09,4.916056e+09,200475.0,0.0,0.0,0.0,26088.061539,95.000000,13.000000,90.250000,116.875000,79.250000,68.375000,22.750000,37.666667,0.253750,4.237500,143.625000,118.250000,109.750000,1.850000,7.012500,9.812500,0.300000,39.250000,36.250000,19.900000,7.320000,422.000000,30.000000,-6.000000,14.285714,1.9,4.0,3.0,0.772193,1663.054187,8530.0,97.500000,33.250000,1.1,29.000000,11.0,0.8,1.925000,10530.0,2000.0,360.0,0.0,0.00,100.0,0,2,1,10,5
1394,100,5,4.915987e+09,4.916070e+09,200475.0,0.0,0.0,0.0,26088.061539,58.000000,13.000000,89.600000,127.600000,86.000000,73.600000,21.000000,37.400000,0.210000,4.500000,144.000000,119.000000,167.600000,2.000000,7.200000,9.700000,0.300000,43.000000,35.500000,23.400000,7.320000,79.000000,37.000000,-3.000000,14.000000,1.9,5.0,2.0,0.702194,376.190476,8435.0,98.000000,34.000000,1.1,29.000000,11.0,0.8,2.300000,10630.0,2195.0,195.0,0.0,0.00,100.0,0,2,1,10,5
1395,100,6,4.915987e+09,4.916084e+09,200475.0,0.0,0.0,0.0,26088.061539,137.800000,13.000000,90.000000,130.833333,87.500000,74.000000,20.333333,37.400000,0.210000,3.966667,144.666667,118.333333,157.000000,2.133333,7.200000,10.033333,0.366667,39.000000,34.300000,22.866667,7.320000,308.000000,41.600000,-3.800000,16.666667,1.9,4.0,2.0,0.687898,1466.666667,8280.0,98.333333,34.666667,1.1,35.666667,23.0,0.8,2.233333,10710.0,2430.0,235.0,0.0,0.00,80.0,0,2,1,10,5
1396,100,7,4.915987e+09,4.916099e+09,200475.0,0.0,0.0,0.0,26088.061539,137.800000,13.000000,97.000000,133.800000,82.800000,67.800000,20.000000,37.400000,0.210000,3.700000,145.000000,118.000000,158.000000,2.200000,7.200000,10.200000,0.400000,37.000000,33.700000,22.600000,7.320000,308.000000,41.600000,-3.800000,18.000000,1.9,4.0,3.0,0.724963,1466.666667,8135.0,98.000000,35.000000,1.1,39.000000,29.0,0.8,2.200000,10790.0,2655.0,225.0,0.0,0.00,80.0,0,2,1,10,5
1397,100,8,4.915987e+09,4.916113e+09,200475.0,0.0,0.0,0.0,26088.061539,70.950000,13.800000,102.000000,142.600000,88.600000,73.400000,20.600000,37.400000,0.210000,3.700000,145.000000,118.000000,186.000000,2.200000,7.200000,10.200000,0.400000,37.000000,33.700000,22.600000,7.348333,380.333333,39.666667,-2.833333,18.000000,1.1,4.0,3.0,0.715288,1811.111111,8005.0,98.800000,35.000000,1.1,39.000000,29.0,0.8,2.200000,10870.0,2865.0,210.0,0.0,0.00,80.0,0,2,1,10,5
1398,100,9,4.915987e+09,4.916128e+09,200475.0,0.0,0.0,0.0,26088.061539,72.000000,14.000000,105.333333,132.666667,85.333333,71.333333,19.333333,37.400000,0.210000,3.700000,145.000000,118.000000,181.333333,2.200000,7.200000,10.200000,0.400000,37.000000,33.700000,22.600000,7.348333,380.333333,39.666667,-2.833333,18.000000,1.1,4.0,2.0,0.793970,1811.111111,8040.0,98.666667,35.000000,1.1,39.000000,29.0,0.8,2.200000,10990.0,2950.0,85.0,0.0,0.00,120.0,0,2,1,10,5
1399,100,10,4.915987e+09,4.916142e+09,200475.0,0.0,0.0,0.0,26088.061539,57.400002,14.000000,103.000000,127.000000,73.500000,59.000000,20.000000,35.992857,0.210000,3.700000,145.000000,118.000000,158.000000,2.200000,7.200000,11.594689,0.400000,37.000000,33.700000,22.600000,7.430000,107.000000,32.000000,-1.000000,18.000000,1.7,4.0,4.0,0.811024,509.523810,8220.0,98.000000,35.000000,1.1,39.000000,29.0,0.8,2.200000,11330.0,3110.0,160.0,0.0,0.00,340.0,0,3,1,15,5
1400,100,11,4.915987e+09,4.916156e+09,200475.0,0.0,0.0,0.0,26088.061539,57.400002,14.000000,103.500000,119.500000,77.500000,68.000000,20.250000,37.400000,0.210000,3.700000,145.000000,118.000000,158.000000,2.200000,7.200000,11.594689,0.400000,37.000000,33.700000,22.600000,7.378000,271.800000,40.800000,-0.600000,18.000000,1.7,4.0,3.0,0.866109,1294.285714,8230.0,97.250000,35.000000,1.1,39.000000,29.0,0.8,2.200000,11530.0,3300.0,190.0,0.0,0.00,200.0,0,3,1,15,5
1401,100,12,4.915987e+09,4.916171e+09,200475.0,0.0,0.0,0.0,26088.061539,57.400002,14.000000,104.000000,123.333333,78.000000,67.666667,21.000000,37.400000,0.210000,3.700000,145.000000,118.000000,158.000000,2.200000,7.200000,11.594689,0.400000,37.000000,33.700000,22.600000,7.430000,107.000000,32.000000,-1.000000,18.000000,1.7,4.0,3.0,0.843243,509.523810,8290.0,97.666667,35.000000,1.1,39.000000,29.0,0.8,2.200000,11730.0,3440.0,140.0,-1.0,0.00,200.0,0,3,1,15,5